[build-system]
requires = ["setuptools>=64", "setuptools-scm>=8"]
build-backend = "setuptools.build_meta"

[project]
name = "osc-veritas"
dynamic = ["version"]
description = "Reference value extraction for CoCo attestation"
authors = [{name = "Beraldo Leal", email = "bleal@redhat.com"}]
requires-python = ">=3.11"
license = "Apache-2.0"

[project.scripts]
veritas = "veritas.__main__:main"

[project.optional-dependencies]
snp = ["sev-snp-measure"]
test = ["pytest"]

[tool.pytest.ini_options]
addopts = "--tb=line --junitxml=report.xml"
junit_family = "xunit1"

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools_scm]
