"""Azure platform reference value extraction."""

import hashlib
import json
import logging
from pathlib import Path

from veritas.container import ContainerImage
from veritas.models import ReferenceValue
from veritas.platforms.base import PlatformExtractor

log = logging.getLogger(__name__)


class AzureExtractor(PlatformExtractor):
    """Extract software measurements from the osc-dm-verity-image."""

    IMAGE_REPO = "registry.redhat.io/openshift-sandboxed-containers/osc-dm-verity-image"
    MEASUREMENTS_PATH = "/image/measurements.json"

    # PCR values scraped from vTPM during UKI podvm boot.
    # Generated by: coco-podvm-scripts/helpers/measure-image.sh
    #   boots podvm.qcow2 with swtpm, runs tpm2_pcrread, scrapes PCRs.
    #   Upstream (cloud-api-adaptor) scrapes 3,9,11.
    #   Red Hat patches it to also scrape 12.
    # PCR meanings per UAPI Group Linux TPM PCR Registry + TCG spec:
    PCR_DESCRIPTIONS = {
        "pcr03": "Pluggable firmware data (OVMF boot config)",
        "pcr09": "Initrd (kernel LOAD_FILE2 protocol)",
        "pcr11": "UKI components (kernel + initrd + cmdline, systemd-stub)",
        "pcr12": "Kernel command line and credentials (systemd-stub)",
    }

    EVIDENCE_TYPES = {
        "tdx": "az_tdx_vtpm",
        "snp": "az_snp_vtpm",
    }

    def __init__(self, tee, authfile=None):
        if tee not in self.EVIDENCE_TYPES:
            raise ValueError(f"Unknown TEE: {tee}. Must be one of {list(self.EVIDENCE_TYPES)}")
        self.tee = tee
        self.image = ContainerImage(self.IMAGE_REPO, authfile=authfile)

    @property
    def platform(self) -> str:
        return "azure"

    @property
    def evidence_type(self) -> str:
        return self.EVIDENCE_TYPES[self.tee]

    def extract(self) -> list[ReferenceValue]:
        """Verify, pull dm-verity image, and parse measurements.json."""
        image_ref = self.image.get_pinned_reference()
        log.info("Image: %s", image_ref)
        log.info("Verifying image signature...")
        self.image.verify(image_ref)
        log.info("Signature verified.")
        self.image.pull(image_ref)
        raw = self.image.extract_file(image_ref, self.MEASUREMENTS_PATH)
        return self._parse_measurements(json.loads(raw))

    def compute_initdata(self, initdata_path: str) -> ReferenceValue:
        """Compute PCR8: sha256(32_zero_bytes || sha256(initdata_content))."""
        content = Path(initdata_path).read_bytes()
        inner = hashlib.sha256(content).digest()
        outer = hashlib.sha256(b"\x00" * 32 + inner).hexdigest()
        return ReferenceValue(
            name="pcr08",
            value=outer,
            category="configuration",
            description="Init data (initdata.toml extended into PCR8)",
            algorithm="sha256",
            source="computed from initdata.toml",
        )

    def _parse_measurements(self, measurements: dict) -> list[ReferenceValue]:
        """Convert measurements.json to ReferenceValues."""
        sha256_data = measurements.get("measurements", {}).get("sha256", {})
        values = []
        for name, description in self.PCR_DESCRIPTIONS.items():
            raw_value = sha256_data.get(name)
            if raw_value is None:
                continue
            values.append(ReferenceValue(
                name=name,
                value=raw_value.lstrip("0x"),
                category="executables",
                description=description,
                algorithm="sha256",
                source="osc-dm-verity-image",
            ))
        return values
