"""Azure platform reference value extraction."""

import hashlib
import json
import logging
from pathlib import Path

from veritas.container import ContainerImage
from veritas.models import ReferenceValue
from veritas.platforms.base import PlatformExtractor
from veritas.platforms.utils import remap_registry

log = logging.getLogger(__name__)


class AzureExtractor(PlatformExtractor):
    """Extract software measurements from the osc-dm-verity-image."""

    DEFAULT_IMAGE_REPO = "registry.redhat.io/openshift-sandboxed-containers/osc-dm-verity-image"
    MEASUREMENTS_PATH = "/image/measurements.json"

    # PCR values scraped from vTPM during UKI podvm boot.
    # Generated by: coco-podvm-scripts/helpers/measure-image.sh
    #   boots podvm.qcow2 with swtpm, runs tpm2_pcrread, scrapes PCRs.
    #   Upstream (cloud-api-adaptor) scrapes 3,9,11.
    #   Red Hat patches it to also scrape 12.
    # PCR meanings per UAPI Group Linux TPM PCR Registry + TCG spec:
    PCR_DESCRIPTIONS = {
        "pcr03": "Pluggable firmware data (OVMF boot config)",
        "pcr09": "Initrd (kernel LOAD_FILE2 protocol)",
        "pcr11": "UKI components (kernel + initrd + cmdline, systemd-stub)",
        "pcr12": "Kernel command line and credentials (systemd-stub)",
    }

    EVIDENCE_TYPES = {
        "tdx": "az_tdx_vtpm",
        "snp": "az_snp_vtpm",
    }

    def __init__(self, tee, authfile=None, image_tags=None, rekor_url=None,
                 rekor_pub_key_url=None, image_repo=None, cosign_pub_key=None,
                 skip_tlog=False, mirror_registry=None):
        if tee not in self.EVIDENCE_TYPES:
            raise ValueError(f"Unknown TEE: {tee}. Must be one of {list(self.EVIDENCE_TYPES)}")
        self.tee = tee
        self.authfile = authfile
        self.image_tags = image_tags or ["latest"]
        self.rekor_url = rekor_url
        self.rekor_pub_key_url = rekor_pub_key_url
        self.image_repo = image_repo or remap_registry(self.DEFAULT_IMAGE_REPO, mirror_registry)
        self.cosign_pub_key = cosign_pub_key
        self.skip_tlog = skip_tlog

    @property
    def platform(self) -> str:
        return "azure"

    @property
    def evidence_type(self) -> str:
        return self.EVIDENCE_TYPES[self.tee]

    ANNOTATION_BASE = "io.github.confidential-containers.measurements"

    def extract(self) -> list[ReferenceValue]:
        """Verify, pull dm-verity image(s), and parse measurements.

        Tries OCI annotations first (no image pull required).
        Falls back to extracting the embedded measurements.json.
        """
        merged = {}
        for tag in self.image_tags:
            log.info("Processing image tag %s", tag)
            image = ContainerImage(self.image_repo, tag=tag, authfile=self.authfile,
                                   rekor_url=self.rekor_url, rekor_pub_key_url=self.rekor_pub_key_url,
                                   cosign_pub_key=self.cosign_pub_key, skip_tlog=self.skip_tlog)
            image_ref = image.get_pinned_reference()
            log.info("Image: %s", image_ref)
            log.info("Verifying image signature...")
            image.verify(image_ref)
            log.info("Signature verified.")
            values = self._measurements_from_annotations(image, image_ref)
            if values is None:
                log.info("No OCI annotations found, falling back to image pull.")
                image.pull(image_ref)
                raw = image.extract_file(image_ref, self.MEASUREMENTS_PATH)
                values = self._parse_measurements(json.loads(raw))
            else:
                log.info("Measurements loaded from OCI annotations.")

            for v in values:
                if v.name in merged:
                    for val in v.values:
                        if val not in merged[v.name].values:
                            merged[v.name].values.append(val)
                else:
                    merged[v.name] = v

        return list(merged.values())

    def compute_initdata(self, initdata_paths: list[str]) -> ReferenceValue:
        """Compute PCR8: sha256(32_zero_bytes || sha256(initdata_content))."""
        digests = []
        for p in initdata_paths:
            content = Path(p).read_bytes()
            inner = hashlib.sha256(content).digest()
            digests.append(hashlib.sha256(b"\x00" * 32 + inner).hexdigest())
        sources = ", ".join(Path(p).name for p in initdata_paths)
        return ReferenceValue(
            name=self._rvps_key("pcr08"),
            values=digests,
            category="configuration",
            description="Init data (initdata.toml extended into PCR8)",
            algorithm="sha256",
            source=f"computed from {sources}",
        )

    def reference_key_names(self) -> set[str]:
        keys = {self._rvps_key(pcr) for pcr in self.PCR_DESCRIPTIONS}
        keys.add(self._rvps_key("pcr08"))
        if self.tee == "tdx":
            keys.add("xfam")
        return keys

    def _rvps_key(self, pcr_name: str) -> str:
        """Convert pcr name to RVPS key: pcr03 -> snp_pcr03 or tdx_pcr03."""
        return f"{self.tee}_{pcr_name}"

    def _measurements_from_annotations(self, image: ContainerImage, image_ref: str) -> list[ReferenceValue] | None:
        """Extract measurements from OCI annotations without pulling the image.

        Expects annotations keyed as:
            io.github.confidential-containers.measurements.algorithm = sha256
            io.github.confidential-containers.measurements.pcr03 = 0x...
            io.github.confidential-containers.measurements.pcr09 = 0x...
            ...

        Returns None if no matching annotations are present.
        """
        try:
            annotations = image.get_annotations(image_ref)
        except RuntimeError:
            return None

        base = self.ANNOTATION_BASE + "."
        alg = annotations.get(base + "algorithm", "sha256")
        pcr_data = {
            k[len(base):]: v
            for k, v in annotations.items()
            if k.startswith(base + "pcr")
        }
        if not pcr_data:
            return None

        return self._parse_measurements({"measurements": {alg: pcr_data}})

    def _parse_measurements(self, measurements: dict) -> list[ReferenceValue]:
        """Convert measurements.json to ReferenceValues."""
        sha256_data = measurements.get("measurements", {}).get("sha256", {})
        values = []
        for name, description in self.PCR_DESCRIPTIONS.items():
            raw_value = sha256_data.get(name)
            if raw_value is None:
                continue
            values.append(ReferenceValue(
                name=self._rvps_key(name),
                values=[raw_value.removeprefix("0x")],
                category="executables",
                description=description,
                algorithm="sha256",
                source="osc-dm-verity-image",
            ))
        return values
