"""Azure platform reference value extraction."""

import hashlib
import json
import logging
from pathlib import Path

from veritas.container import ContainerImage
from veritas.models import ReferenceValue
from veritas.platforms.base import PlatformExtractor

log = logging.getLogger(__name__)


class AzureExtractor(PlatformExtractor):
    """Extract software measurements from the osc-dm-verity-image."""

    IMAGE_REPO = "registry.redhat.io/openshift-sandboxed-containers/osc-dm-verity-image"
    MEASUREMENTS_PATH = "/image/measurements.json"

    # PCR values scraped from vTPM during UKI podvm boot.
    # Generated by: coco-podvm-scripts/helpers/measure-image.sh
    #   boots podvm.qcow2 with swtpm, runs tpm2_pcrread, scrapes PCRs.
    #   Upstream (cloud-api-adaptor) scrapes 3,9,11.
    #   Red Hat patches it to also scrape 12.
    # PCR meanings per UAPI Group Linux TPM PCR Registry + TCG spec:
    PCR_DESCRIPTIONS = {
        "pcr03": "Pluggable firmware data (OVMF boot config)",
        "pcr09": "Initrd (kernel LOAD_FILE2 protocol)",
        "pcr11": "UKI components (kernel + initrd + cmdline, systemd-stub)",
        "pcr12": "Kernel command line and credentials (systemd-stub)",
    }

    EVIDENCE_TYPES = {
        "tdx": "az_tdx_vtpm",
        "snp": "az_snp_vtpm",
    }

    def __init__(self, tee, authfile=None, osc_versions=None):
        if tee not in self.EVIDENCE_TYPES:
            raise ValueError(f"Unknown TEE: {tee}. Must be one of {list(self.EVIDENCE_TYPES)}")
        self.tee = tee
        self.authfile = authfile
        self.osc_versions = osc_versions or ["latest"]

    @property
    def platform(self) -> str:
        return "azure"

    @property
    def evidence_type(self) -> str:
        return self.EVIDENCE_TYPES[self.tee]

    def extract(self) -> list[ReferenceValue]:
        """Verify, pull dm-verity image(s), and parse measurements.json."""
        merged = {}
        for tag in self.osc_versions:
            log.info("Processing OSC %s", tag)
            image = ContainerImage(self.IMAGE_REPO, tag=tag, authfile=self.authfile)
            image_ref = image.get_pinned_reference()
            log.info("Image: %s", image_ref)
            log.info("Verifying image signature...")
            image.verify(image_ref)
            log.info("Signature verified.")
            image.pull(image_ref)
            raw = image.extract_file(image_ref, self.MEASUREMENTS_PATH)
            values = self._parse_measurements(json.loads(raw))

            for v in values:
                if v.name in merged:
                    for val in v.values:
                        if val not in merged[v.name].values:
                            merged[v.name].values.append(val)
                else:
                    merged[v.name] = v

        return list(merged.values())

    def compute_initdata(self, initdata_path: str) -> ReferenceValue:
        """Compute PCR8: sha256(32_zero_bytes || sha256(initdata_content))."""
        content = Path(initdata_path).read_bytes()
        inner = hashlib.sha256(content).digest()
        outer = hashlib.sha256(b"\x00" * 32 + inner).hexdigest()
        return ReferenceValue(
            name=self._rvps_key("pcr08"),
            values=[outer],
            category="configuration",
            description="Init data (initdata.toml extended into PCR8)",
            algorithm="sha256",
            source="computed from initdata.toml",
        )

    def _rvps_key(self, pcr_name: str) -> str:
        """Convert pcr name to RVPS key: pcr03 -> snp_pcr03 or tdx_pcr03."""
        return f"{self.tee}_{pcr_name}"

    def _parse_measurements(self, measurements: dict) -> list[ReferenceValue]:
        """Convert measurements.json to ReferenceValues."""
        sha256_data = measurements.get("measurements", {}).get("sha256", {})
        values = []
        for name, description in self.PCR_DESCRIPTIONS.items():
            raw_value = sha256_data.get(name)
            if raw_value is None:
                continue
            values.append(ReferenceValue(
                name=self._rvps_key(name),
                values=[raw_value.lstrip("0x")],
                category="executables",
                description=description,
                algorithm="sha256",
                source="osc-dm-verity-image",
            ))
        return values
